### ISSUE TITLE
error: overlap is not transmuted!

### ISSUE THREAD

**Issue by aliexclusive** [isovic/racon#132]
Dear Team,

I'm using Racon 1.4.0 and trying to polish the assembly using Illumina reads. 

```
racon -t 64 NP_trim.fq assembly_minimap_il.paf assembly_raconNP_medaka2x.fa > assembly_raconNP_medaka2x_raconILM.fa
```

Here is my jobscript.

```
#SBATCH -N 1
#SBATCH --ntasks-per-node=64
#SBATCH --partition=batch
#SBATCH -J medaka
#SBATCH -o racon.%J.out
#SBATCH -e racom.%J.err
#SBATCH --time=24:00:00
#SBATCH --mem=200G
```

I'm getting the following error.

```
[racon::Polisher::initialize] loaded target sequences 1.513 s
[racon::Polisher::initialize] loaded sequences 85.565 s
[racon::Polisher::initialize] loaded overlaps 42.113 s
[racon::Overlap::find_breaking_points] error: overlap is not transmuted!
```

Any suggestion, how can I solve this issue.

**Comment by rvaser** [comment]
Hello,
can you please paste the command that produced `assembly_minimap_il.paf`?

Best regards,
Robert

**Comment by aliexclusive** [comment]
Here it is

`minimap2 -x sr assembly_raconNP_medaka2x.fa IL_trim.fq > assembly_minimap_il.paf`

**Comment by rvaser** [comment]
I guess you misplaced the read file in your racon command, i.e. instead of `IL_trim.fq` you used `NP_trim.fq`. The valid command should look like this:

`racon -t 64 IL_trim.fq assembly_minimap_il.paf assembly_raconNP_medaka2x.fa > assembly_raconNP_medaka2x_raconILM.fa`

The errors `overlap is not transmuted` or `empty overlap set` indicate that the overlap file does not contain both the sequence headers and contig headers.

Best regards,
Robert

**Comment by aliexclusive** [comment]
It worked fine. Thanks for your kind guidance.
