### ISSUE TITLE
Multiple rounds of polishing

### ISSUE THREAD

**Issue by 000generic** [isovic/racon#160]
Given TGS and SGS reads, I've read in some of the issues that multiple rounds of TGS polishing followed by multiple rounds of SGS polishing is being used. Is this generally recommended? If so, I was wondering:

1) Should reads be remapped in between each round of polishing?

2) What methods or software are recommended or commonly used for evaluating and comparing (sequentially) polished transcriptomes?

I was initially going to do Racon TGS -> Racon SGS -> Pilon SGS  but can try including multiple rounds at the Racon steps, if its generally thought to improve things.

**Comment by rvaser** [comment]
Hello Eric,
your intended approach should suffice, there is no need for more iterations when you have SGS data. In case of multiple iterations with the same dataset, you need to remap between each round of polishing. I am unaware of any methods for sequential polishing and evaluation of transcriptomes. Also, I am not sure if Racon will work properly on transcripts due to alternative splicing.

Best regards,
Robert

Best regards,
Robert

**Comment by 000generic** [comment]
Hi Robert,

Great!  Thank you for all the details. 

Eric
