### ISSUE TITLE
two files are missing

### ISSUE THREAD

**Issue by wsuplantpathology** [isovic/racon#19]
Hello Racon:

I plan to run Racon using example data, following your instruction. However, it seems there are two files missing. 

First, in your 'Quick start' section, it says: 
Run an example script:

`./example1-paf-lambda.sh` 

However, it seems there is no such a file in racon/ directory.

Second, in 'Usage' section, it says:
Consensus from mappings/overlaps in PAF/MHAP format

Generate mappings of reads to the layout using, e.g., Minimap:
`tools/minimap/minimap test-data/lambda/layout-miniasm.gfa.fasta test-data/lambda/reads.fastq > test-data/lambda/mappings.paf  `
Again, there is no file called 'layout-miniasm.gfa.fasta' in test-data/lambda/ directory. Instead, I can find this 'layout-miniasm.gfa'. 

So, how to find these files? Thanks.

**Comment by isovic** [comment]
Hi,
you are right - these files are not present, it seems we forgot to update the README - thanks for reporting!
Since the time ```./example1-paf-lambda.sh``` was used, Racon was extended to support ```.paf``` input alongside to ```.mhap```, so the example 1 script now has two versions: ```example1_1-paf-lambda-align.sh``` and ```example1_2-mhap-lambda.sh``` which are virtually the same except for a line which converts PAF mappings to MHAP (https://github.com/isovic/racon/blob/master/example1_2-mhap-lambda.sh#L47).

As for the missing ```test-data/lambda/layout-miniasm.gfa.fasta```, it needs to be generated from the GFA, e.g. using awk:
```awk '$1 ~/S/ {print ">"$2"\n"$3}' test-data/lambda/layout-miniasm.gfa > test-data/lambda/layout-miniasm.gfa.fasta```  
(it's generated automatically when you run the above example scripts; https://github.com/isovic/racon/blob/master/example1_2-mhap-lambda.sh#L20)

I'll leave this open until we update the README.

Best regards,
Ivan.

**Comment by isovic** [comment]
P.S. Also, before running example scripts, run ```make tools``` to install ```dnadiff``` and other tools for evaluation of the results.

Ivan

**Comment by rvaser** [comment]
Version 1.0.0 has sample data in 'test/data/' which can be automatically run if you build racon with unit tests (i.e. add -Dbuild_racon_tests=ON to cmake command) and run 'bin/racon_test'.
