### ISSUE TITLE
racon support fasta as reads

### ISSUE THREAD

**Issue by mictadlo** [isovic/racon#28]
Hi,
Does racon support fasta as reads rather than fastq files?

Thank you in advance.

Michal

**Comment by rvaser** [comment]
Hello Michal,
Racon was designed to use base quality values for better accuracy. If you do not have them, transform your FASTA file into FASTQ with uniform dummy qualities (for example, set them to '*' and disable the quality filter with '--bq -1').

Best regards,
Robert

**Comment by ebioman** [comment]
Hi
I would like to pitch in here. I am struggling for a large genome with memory issues as all my reads (400GB) are too large for the memory. Obviously, if I remove the quality information this shrinks to <200GB.
Regarding the fact that all newer PacBio (Sequel) data do **not** contain quality values anymore FASTA support would be really great. By providing such an option directly in Racon instead of generating then dummy quality values instead one would save a lot of time, space and memory.
What do you think?
Cheers

**Comment by rvaser** [comment]
Hello,
sorry for the delayed response. Racon was designed to use base quality values and leaving them out might yield lower accuracy. We are in the middle of a refactor and we are considering to enable FASTA reads as input, but more evaluation is needed.

Best regards,
Robert

**Comment by faguil** [comment]
Hi everyone,

I really want to use Racon for polishing/consensus; however, my PacBio reads are in fasta format and I have no access to original files to get fastq reads. So, I am wondering if there is a way of using PacBio fasta reads instead of fastq files. 

I have read here and in other post that you can give uniform quality scores to my PacBio fasta file and set up the --bq -1 parameter to skip quality score checking during Racon runnung. Do you know any script/software to do that, I tried reformat.sh from the BBMAP package but it did not work. 

Any help would be really appreciated. 

Thanks in advance, 

Felipe

**Comment by rvaser** [comment]
Hi Felipe,
I wrote you a quick python script which should do the job https://pastebin.com/Wf0iZEVf. Run it with `python script.py file.fasta > file.fastq`

Best regards,
Robert

**Comment by faguil** [comment]
Hi Robert,

Thank you so much for your help, I will give a try to your script. Thanks again for your quick response.

**Comment by rvaser** [comment]
Racon 1.0.0 now supports direct FASTA input!
