### ISSUE TITLE
ERROR] #5: Could not find qname 'blah-blah' in the input contigs file!

### ISSUE THREAD

**Issue by alducluzeau** [isovic/racon#31]
Hi there !

It's the first time I use racon and I encounter this error message:
"ERROR] #5: Unexpected value found! Could not find qname '645a46de-26ef-41ac-8006-7d49097c69c4' in the input contigs file! Exiting. In function: 'ParsePAF"
I saw that there was a previous post open on a similar issue. Thus, I took a look at my .paf format which is fine I think.
It seems that racon complains that the read in question is not in the .gfa. I checked this and indeed it is not included in it while it figures in the .paf. My guess is that is not included in the .gfa because it wasn't use to build the final contigs and fell off the assembly. 

Thus, I feel I am missing something here. Does racon necessitate the usage of an option in miniasm that would output the unused reads in the .gfa ? If it does, I wasn't able to find it. 
I am sure this will sound very candide question. Sorry for that...

Thank you !

AL

**Comment by isovic** [comment]
Hi,

Could you post the exact command lines you used to run Racon?

I have a feeling that you are feeding Racon the read-to-read overlaps .paf file (which you used to generate the assembly with Miniasm), instead of read-to-reference mappings.
In other words, after the layout phase of Miniasm is done, reads need to be mapped to the obtained layout (e.g. using Minimap, which produces another .paf).

Hope this helps,
Best regards,
Ivan.

**Comment by alducluzeau** [comment]
Hi Ivan,

Thank you so much for answering to me so quickly. 

You’re right: I used the read-toread overlaps file instead of the other. I was totally unaware of this function of minimap.
Now it makes more sense. 
As you can guess, I’m a microbiologist moving to bioinformatics. Thus, I frequently miss points like that.
I really do appreciate that you took the time to answer my naive question in such an easy way to understand.

Thank you again and have a great week-end !

Anne-Lise D.
