### ISSUE TITLE
/usr/bin/time and dnadiff not found

### ISSUE THREAD

**Issue by eburgueno** [isovic/racon#42]
After compilation, I tried running the `./example1_1-paf-lambda-align.sh` script, but it's failing because it assumes `/usr/bin/time` and `dnadiff` are present. These are not mentioned as prerequisites.

Based on #19, `dnadiff` should be created by the `make` commands at the beginning of the script, but this shouldn't be necessary if the installation instructions were followed and worked.

The installation instructions should also include which paths should be added to the user's PATH, other than `$PREFIX/bin`

**Comment by isovic** [comment]
Hi,
These are not mentioned as prerequisites as they are not required to run Racon - the example script simply demonstrates how to run it, measure memory/time consumption and compare the results.
Dnadiff is part of the very widely used package Mummer, which is available on `apt` (if you use Debian) and many other package managing systems, but it's also fairly simple to compile from source.
May I ask which OS are you running Racon on?
The `/usr/bin/time` used in the script is the GNU one, which unfortunately is not compatible with MacOS's BSD version due to different parameters.

With all of the above, we should definitely update the example scripts in the next release.
I'm marking this thread as Enhancement.

Best regards,
Ivan.

**Comment by eburgueno** [comment]
> Dnadiff is part of the very widely used package Mummer, which is available on apt (if you use Debian) and many other package managing systems, but it's also fairly simple to compile from source.

Thanks, did not know that. You can ignore that part then :)

> May I ask which OS are you running Racon on?

We are using CentOS 7 in our cluster. The OS image is based on CentOS 7 minimal, which does not install the `time.x86_64` package by default so instead you just use the shell keyword.

Since this is flagged as an enhancement, I would suggest that on the example scripts you test if `/usr/bin/time` or `time` exist, and if not just run Racon without the time stats (maybe even with a message indicating so).

**Comment by isovic** [comment]
> Thanks, did not know that. You can ignore that part then :)
No worries! :-)

> We are using CentOS 7 in our cluster. The OS image is based on CentOS 7 minimal, which does not install the time.x86_64 package by default so instead you just use the shell keyword.

> Since this is flagged as an enhancement, I would suggest that on the example scripts you test if /usr/bin/time or time exist, and if not just run Racon without the time stats (maybe even with a message indicating so).

Good suggestion, thanks!

Ivan

**Comment by rvaser** [comment]
Example scripts were removed in Racon 1.0.0.
