### ISSUE TITLE
ERROR: Reads are not specified in a format which contains quality information. - only for SAM input.

### ISSUE THREAD

**Issue by bsipos** [isovic/racon#43]
When I run racon as `racon  --sam -t 40 --use-contig-qv --bq 5` on [this](https://gist.github.com/bsipos/643deabf768db0f5e4dab1dc1dff31e4) dataset I get the error:

```
[15:41:00 main] Using SAM for input alignments. (...)
[15:41:00 main] Parsing the SAM file.
ERROR: Reads are not specified in a format which contains quality information. Exiting.
```

If I use PAF input then racon runs successfully.

**Comment by rvaser** [comment]
Hello,
the error indicates that some of the sequences in the SAM file do not have their qualities. Is something missing in your SAM file you posted on gist (it ends abruptly)?

Best regards,
Robert

**Comment by bsipos** [comment]
Hi,

The SAM file is not truncated, it converts to BAM cleanly. But it does contain secondary and supplementary alignments. I have noticed that minimap2 sometimes omits the sequence field for those. Maybe that is the issue?

Best,
Botond

**Comment by isovic** [comment]
Hi Botond,

> I have noticed that minimap2 sometimes omits the sequence field for those.
In those cases it does not generate either seq nor qual fields?
It does makes sense to generate such an output to save space, since all the info should be in the primary alignments. Unfortunately, we did not anticipate for that and this is the likely cause of the issue you are having, because Racon currently expects that each SAM entry has both of those fields defined (each SAM alignment is viewed as a separate object).
We will address this in the next release or soon, but for now I would recommend filtering out those secondary alignments which do not have the seq and qual fields.

Best regards,
Ivan.

**Comment by bsipos** [comment]
Thanks Ivan!

Yes, it seems that minimap2 does omit the seq and qual fields for some non-primary alignments which explains the error. I will either do filtering or stick to the PAF input until the issue is fixed.

Cheers,
Botond

**Comment by isovic** [comment]
Np, I'll leave this open to keep track.

Ivan

**Comment by rvaser** [comment]
Racon 1.0.0 now supports minimap2 SAM output.
