### ISSUE TITLE
racon progress? verbose mode?

### ISSUE THREAD

**Issue by migrau** [isovic/racon#55]
I am running racon with:
`racon raw.fq reads2.paf contigs.fasta -t 4`

The only ouput text is:
`[racon::Polisher::initialize] loaded target sequences`

Using `top` command, I can't see any job related with racon running. There is any verbose mode to see if it is actually running? 

racon version is v1.0.0. Very small organism: fq is 184M, fasta 16K, paf: 2M.

Thanks,

**Comment by rvaser** [comment]
Hello,
that is quite odd. There isn't a more verbose output, the next step is simple read parsing. Maybe there is an infinite loop somewhere. Would you mind sending me your files so I can see what happens?

Best regards,
Robert

**Comment by rvaser** [comment]
If you by any chance did not get the email, I was able to get past the point your program hung (loaded target sequences) assuming you have sent me the same data. Nonetheless, Racon breaks later because read cc8621e7-c603-4ef8-a09f-d80485456f97 has mismatching length in .paf and .fq files (3671 vs 4045). I ran minimap on reads and contigs you have sent me and Racon finishes without problems. Could you please verify if you have sent me the same data causing the error you encountered?

Best regards,
Robert

**Comment by migrau** [comment]
Hi Robert, Many thanks for your help. I was away last week but I will re-check the input data to identify the mismatching length. Anyway, it is a bit weird, why I don't receive the error? Run it on a HPC can be a problem? 

Cheers, 
Miquel

**Comment by rvaser** [comment]
I doubt that HPC might cause the problem, although racon will only use one node (full support for HPC might be added later). Try running the latest release with the same command that caused your error and please do check the input :)

**Comment by migrau** [comment]
rvaser, it works now. Not sure what was the problem. As you said, now I received the error, and after re-generate the paf file with minimap, if finished correctly. Thanks!
